AgroliteracyOntology/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('',include('ontology.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ontology/urls.py
from django.urls import path
from . import views
app_name='ontology'

urlpatterns=[
    path('',views.index,name='index'),
    path('knowledge_center_login/',views.knowledge_center_login,name='knowledge_center_login'),
    path('knowledge_center_home/',views.knowledge_center_home,name='knowledge_center_home'),
    path('manage_farmer/',views.manage_farmer,name='manage_farmer'),
    path('approve_farmer/<int:id>/',views.approve_farmer,name='approve_farmer'),
    path('reject_farmer/<int:id>/',views.reject_farmer,name='reject_farmer'),
    path('manage_dealer/',views.manage_dealer,name='manage_dealer'),
    path('approve_dealer/<int:id>/',views.approve_dealer,name='approve_dealer'),
    path('reject_dealer/<int:id>/',views.reject_dealer,name='reject_dealer'),
    path('add_knowledge_center_notification/',views.add_knowledge_center_notification,name='add_knowledge_center_notification'),
    path('add_knowledge_center_service/',views.add_knowledge_center_service,name='add_knowledge_center_service'),
    path('knowledge_center_select_category/',views.knowledge_center_select_category,name='knowledge_center_select_category'),
    path('knowledge_center_select_subcategory/',views.knowledge_center_select_subcategory,name='knowledge_center_select_subcategory'),
    path('knowledge_center_add_product/<int:id>/',views.knowledge_center_add_product,name='knowledge_center_add_product'),
    path('manage_stock/',views.manage_stock,name='manage_stock'),
    path('admin_update_stock/<int:id>/',views.admin_update_stock,name='admin_update_stock'),
    path('delete_admin_product/<int:id>/',views.delete_admin_product,name='delete_admin_product'),
    path('view_all_farmers/',views.view_all_farmers,name='view_all_farmers'),
    path('view_all_dealers/',views.view_all_dealers,name='view_all_dealers'),
    path('knowledge_center_view_all_products/',views.knowledge_center_view_all_products,name='knowledge_center_view_all_products'),
    path('view_complaints/',views.view_complaints,name='view_complaints'),
    path('send_complaint_replay/<int:id>/',views.send_complaint_replay,name='send_complaint_replay'),
    path('view_questions/',views.view_questions,name='view_questions'),
    path('send_question_replay/<int:id>/',views.send_question_replay,name='send_question_replay'),
    path('admin_view_notification/',views.admin_view_notification,name='admin_view_notification'),
    path('farmer_reg/',views.farmer_reg,name='farmer_reg'),
    path('dealer_reg/',views.dealer_reg,name='dealer_reg'),
    path('farmer_login/',views.farmer_login,name='farmer_login'),
    path('farmer_home/<int:id>/', views.farmer_home, name='farmer_home'),
    path('view_farmer_profile/<int:id>/', views.view_farmer_profile, name='view_farmer_profile'),
    path('view_services/<int:id>/',views.view_services,name='view_services'),
    path('view_product_cat/',views.view_product_cat,name='view_product_cat'),
    path('view_product_sub_cat/<int:id>/',views.view_product_sub_cat,name='view_product_sub_cat'),
    path('show_products/<int:id>/',views.show_products,name='show_products'),
    path('show_single_product/<int:id>/',views.show_single_product,name='show_single_product'),
    path('farmer_buy_product/<int:id>/',views.farmer_buy_product,name='farmer_buy_product'),
    path('make_payment/<int:id>/',views.make_payment,name='make_payment'),
    path('payed/<int:id>/',views.payed,name='payed'),
    path('rent_equipments/',views.rent_equipments,name='rent_equipments'),
    path('show_single_equipments/<int:id>/',views.show_single_equipments,name='show_single_equipments'),
    path('farmer_rent_equipments/<int:id>/',views.farmer_rent_equipments,name='farmer_rent_equipments'),
    path('send_complaint/<int:id>/',views.send_complaint,name='send_complaint'),
    path('farmer_view_replay/<int:id>/',views.farmer_view_replay,name='farmer_view_replay'),
    path('add_question/<int:id>/',views.add_question,name='add_question'),
    path('farmer_view_question_replay/<int:id>/',views.farmer_view_question_replay,name='farmer_view_question_replay'),
    path('farmer_view_payment_detail/',views.farmer_view_payment_detail,name='farmer_view_payment_detail'),
    path('farmer_view_notification/',views.farmer_view_notification,name='farmer_view_notification'),
    path('farmer_change_password/<int:id>/',views.farmer_change_password,name='farmer_change_password'),
    path('contact_dealer/<int:id>/',views.contact_dealer,name='contact_dealer'),
    path('contact_send/<int:id>/',views.contact_send,name='contact_send'),
    path('contact_knowledge_center/<int:id>/',views.contact_knowledge_center,name='contact_knowledge_center'),
    path('dealer_login/',views.dealer_login,name='dealer_login'),
    path('dealer_home/<int:id>/',views.dealer_home,name='dealer_home'),
    path('view_dealer_profile/<int:id>/',views.view_dealer_profile,name='view_dealer_profile'),
    path('add_subcategory/<int:id>/',views.add_subcategory,name='add_subcategory'),
    path('select_category/<int:id>/',views.select_category,name='select_category'),
    path('select_subcategory/<int:id>/',views.select_subcategory,name='select_subcategory'),
    path('add_product/<int:id>/',views.add_product,name='add_product'),
    path('view_all_products/',views.view_all_products,name='view_all_products'),
    path('update_product_stock/<int:id>/',views.update_product_stock,name='update_product_stock'),
    path('delete_dealer_product/<int:id>/',views.delete_dealer_product,name='delete_dealer_product'),
    path('add_dealer_notification/<int:id>/',views.add_dealer_notification,name='add_dealer_notification'),
    path('view_all_payment_detail/',views.view_all_payment_detail,name='view_all_payment_detail'),
    path('approve_order/<int:id>/',views.approve_order,name='approve_order'),
    path('reject_order/<int:id>/',views.reject_order,name='reject_order'),
    path('view_all_delivery_status/',views.view_all_delivery_status,name='view_all_delivery_status'),
    path('product_delivered/<int:id>/',views.product_delivered,name='product_delivered'),
    path('product_not_delivered/<int:id>/',views.product_not_delivered,name='product_not_delivered'),
    path('dealer_view_notification/',views.dealer_view_notification,name='dealer_view_notification'),
    path('dealer_change_password/<int:id>/',views.dealer_change_password,name='dealer_change_password'),
    path('logout/',views.logout,name='logout'),
]

ontology/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Farmer,Dealer,Product,Category,DealerNotification,KnowledgeCenterService,KnowledgeCenterNotification,Order,Rent,Complaint,Question,Subcategory
from .forms import FarmerLoginForm,FarmerRegForm,DealerLoginForm,DealerRegForm,FarmerUpdateForm,AddProductForm,CategoryForm,ReplayComplaintForm,SubcategoryForm
from .forms import DealerNotificationForm,DealerUpdateForm,KnowledgeCenterNotificationForm,KnowledgeCenterServiceForm,ComplaintForm,QuestionForm,ReplayQuestionForm,ChangePassForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib import messages
from datetime import date
from django.views.decorators.csrf import csrf_exempt


def index(request):
    return render(request,'ontology/index.html')


def knowledge_center_login(request):
    
    return render(request, 'ontology/knowledge_center_login.html', {'form': form})


def knowledge_center_home(request):
    if request.session.has_key:
        username = request.session['email']
        sid = request.session['sid']
        return render(request, 'ontology/knowledge_center_home.html', {'name': username, 'sid': sid})


def manage_farmer(request):
    q=Farmer.objects.filter(Status=False)
    return render(request,'ontology/manage_farmer.html',{'q':q})


def approve_farmer(request,id):
    qr=Farmer.objects.get(id=id)
    qr.Status=1
    qr.save()
    return redirect('/manage_farmer')


def reject_farmer(request,id):
    qr=Farmer.objects.get(id=id)
    qr.Status=0
    qr.save()
    return redirect('/manage_farmer')


def manage_dealer(request):
    q=Dealer.objects.filter(Status=False)
    return render(request,'ontology/manage_dealer.html',{'q':q})


def approve_dealer(request,id):
    qr=Dealer.objects.get(id=id)
    qr.Status=1
    qr.save()
    return redirect('/manage_dealer')


def reject_dealer(request,id):
    qr=Dealer.objects.get(id=id)
    qr.Status=0
    qr.save()
    return redirect('/manage_dealer')


def add_knowledge_center_notification(request):
    sid = request.session['sid']
    admin=User.objects.get(id=sid)
    if request.method == 'POST':
        form = KnowledgeCenterNotificationForm(request.POST)
        if form.is_valid():
            notification = form.cleaned_data['Notification']
            res = KnowledgeCenterNotification(Notification=notification)
            res.save()
            messages.success(request, "Notification added successfully")
            return redirect('/knowledge_center_home')
    else:
        form = KnowledgeCenterNotificationForm()
    return render(request, 'ontology/add_knowledge_center_notification.html', {'form': form,'admin':admin})


def knowledge_center_select_category(request):
    sid = request.session['sid']
    admin = User.objects.get(id=sid)
    category=Category.objects.all()
    return render(request,'ontology/knowledge_center_select_category.html',{'category':category,'admin':admin})


def knowledge_center_select_subcategory(request):
    sid = request.session['sid']
    admin = User.objects.get(id=sid)
    cat = request.POST.get('Category')
    request.session['cat']=cat
    sub=Subcategory.objects.filter(Category=cat)
    subcat =request.POST.get('Subcategory')
    if subcat:
        subcat=Subcategory.objects.filter(id=subcat)
        return redirect('/knowledge_center_add_product/%s' % subcat)
    return render(request,'ontology/knowledge_center_select_subcategory.html',{'admin':admin,'category':cat,'sub':sub})


def knowledge_center_add_product(request,id):
    sid = request.session['sid']
    admin = User.objects.get(id=sid)
    cat=request.session['cat']
    subcat=request.POST.get('Subcategory')
    sub=Subcategory.objects.get(id=id)
    category=Category.objects.get(id=cat)
    if request.method=='POST':
        form=AddProductForm(request.POST,request.FILES)
        if form.is_valid():
            name=form.cleaned_data['Name']
            price=form.cleaned_data['Price']
            rent_amount=form.cleaned_data['Rent_Amount']
            quantity=form.cleaned_data['Quantity']
            photo=form.cleaned_data['Photo']
            use=form.cleaned_data['Use']
            res=Product(OwnerId=sid,OwnerName=admin.username,Category=category,Subcategory=sub,Name=name,Price=price,Rent_Amount=rent_amount,
                        Quantity=quantity,Photo=photo,Use=use)
            res.save()
            messages.success(request,"Product added!")
            msg = "Product added Successfully"
            return render(request, 'ontology/knowledge_center_add_product.html', {'form': form,'category':category, 'admin': admin, 'msg': msg})
    else:
        form=AddProductForm()
    return render(request,'ontology/knowledge_center_add_product.html',{'form':form,'admin':admin,'sub':sub})


def add_knowledge_center_service(request):
    sid = request.session['sid']
    admin=User.objects.get(id=sid)
    if request.method == 'POST':
        form = KnowledgeCenterServiceForm(request.POST)
        if form.is_valid():
            service = form.cleaned_data['Service']
            res = KnowledgeCenterService(Service=service)
            res.save()
            messages.success(request, "Service added successfully")
            return redirect('/knowledge_center_home')
    else:
        form = KnowledgeCenterServiceForm()
    return render(request, 'ontology/add_knowledge_center_service.html', {'form': form,'admin':admin})


def view_all_farmers(request):
    sid = request.session['sid']
    admin = User.objects.get(id=sid)
    farmer=Farmer.objects.filter(Status=True)
    return render(request,'ontology/view_all_farmers.html',{'admin':admin,'farmer':farmer})


def view_all_dealers(request):
    sid = request.session['sid']
    admin = User.objects.get(id=sid)
    dealer=Dealer.objects.filter(Status=True)
    return render(request,'ontology/view_all_dealers.html',{'admin':admin,'dealer':dealer})


def knowledge_center_view_all_products(request):
    sid = request.session['sid']
    admin = User.objects.get(id=sid)
    product=Product.objects.all()
    return render(request,'ontology/knowledge_center_view_all_products.html',{'admin':admin,'product':product})


def view_complaints(request):
    sid = request.session['sid']
    admin = User.objects.get(id=sid)
    complaint=Complaint.objects.all()
    return render(request,'ontology/view_complaints.html',{'admin':admin,'complaint':complaint})


def send_complaint_replay(request,id):
    sid = request.session['sid']
    admin = User.objects.get(id=sid)
    complaint = Complaint.objects.get(id=id)
    farmer=Farmer.objects.get(id=complaint.farmer_id)
    if request.method=='POST':
        form=ReplayComplaintForm(request.POST)
        if form.is_valid():
            replay=form.cleaned_data['replay']
            complaint.replay_date=date.today()
            complaint.replay=replay
            complaint.save()
            messages.success(request,"Replay send!")
            return redirect('/view_complaints')
    else:
        form=ReplayComplaintForm()
    return render(request,'ontology/send_complaint_replay.html',{'form':form,'admin':admin,'complaint':complaint})


def view_questions(request):
    sid = request.session['sid']
    admin = User.objects.get(id=sid)
    question=Question.objects.all()
    return render(request,'ontology/view_questions.html',{'admin':admin,'question':question})


def send_question_replay(request,id):
    sid = request.session['sid']
    admin = User.objects.get(id=sid)
    question=Question.objects.get(id=id)
    farmer=Farmer.objects.get(id=question.farmer_id)
    if request.method=='POST':
        form=ReplayQuestionForm(request.POST)
        if form.is_valid():
            replay=form.cleaned_data['replay']
            question.replay=replay
            question.replay_date=date.today()
            question.save()
            messages.success(request,"Replay Send!")
            return redirect('/view_questions')
    else:
        form=ReplayQuestionForm()
    return render(request,'ontology/send_question_replay.html',{'form':form,'admin':admin,'question':question})


def admin_view_notification(request):
    sid = request.session['sid']
    admin = User.objects.get(id=sid)
    notification=DealerNotification.objects.all()
    return render(request,'ontology/admin_view_notification.html',{'admin':admin,'notification':notification})


def manage_stock(request):
    sid = request.session['sid']
    admin = User.objects.get(id=sid)
    product=Product.objects.filter(OwnerId=sid,OwnerName=admin.username)
    return render(request,'ontology/manage_stock.html',{'admin':admin,'product':product})


def admin_update_stock(request,id):
    sid = request.session['sid']
    admin = User.objects.get(id=sid)
    product=Product.objects.get(id=id)
    form=AddProductForm(request.POST or None,instance=product)
    if form.is_valid():
        form.save()
        return redirect('/manage_stock')
    return render(request,'ontology/admin_update_stock.html',{'form':form,'product':product,'admin':admin})


def delete_admin_product(request,id):
    sid = request.session['sid']
    admin = User.objects.get(id=sid)
    product = Product.objects.get(id=id)
    product.delete()
    return redirect('/manage_stock')


def farmer_reg(request):
    if request.method=='POST':
        form=FarmerRegForm(request.POST,request.FILES)
        if form.is_valid():
            firstname=form.cleaned_data['Firstame']
            lastname=form.cleaned_data['Lastname']
            gender=form.cleaned_data['Gender']
            address=form.cleaned_data['Address']
            email=form.cleaned_data['Email']
            place=form.cleaned_data['Place']
            photo=request.POST.get('Photo')
            phone=form.cleaned_data['Phone']
            village=form.cleaned_data['Village']
            district=form.cleaned_data['District']

ontology/templates/ontology/farmer_login.html
{% load static %}
<html lang="en">
<head>
<title>AgroPlus</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<script src="{% static 'js/jquery-1.7.1.min.js' %}"></script>
<script src="{% static 'js/superfish.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/tms-0.4.1.js' %}"></script>
<script src="{% static 'js/slider.js' %}"></script>
<!--[if lt IE 9]>
<script src="{% static 'js/html5.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/ie.css' %}">
<![endif]-->
</head>
<body>
<div class="main-bg">
  <!-- Header -->
  <header>
    <div class="inner">
      <h1 class="logo"><a href="{%url 'ontology:index' %}">AgroPlus - Agriculture company</a></h1>
      <nav>
        <ul class="sf-menu">
          <li class="current"><a href="{%url 'ontology:index' %}">home</a></li>
          <li> <a href="#">Login</a>
            <ul>
                <li><a href="{%url 'ontology:farmer_login' %}">Farmer</a></li>
                <li><a href="{%url 'ontology:dealer_login' %}">Dealer</a></li>
                <li><a href="{%url 'ontology:knowledge_center_login' %}">Knowledge Center</a></li>
            </ul>
          </li>
          <li><a href="#">about</a></li>
        </ul>
      </nav>
      <div class="clear"></div>
    </div>

  </header>
  <!-- Content -->
  <section id="content">
    <div class="container_24">
      <div class="wrapper">
        <div class="grid_24 content-bg">
          <div class="wrapper">
            <div class="grid_16 suffix_1 prefix_1 alpha">




                <center>
    {% if error %}
        <p style="color:red">{{error}}</p>
        {% endif %}
<h3>Farmer Login here</h3>
        <form action="{%url 'ontology:farmer_login' %}" method="post">
            {% csrf_token %}
            <table align="center">
            {{form.as_table}}
            <tr><td></td><td>
            <input type="submit" value="Login">
                </td></tr>
                </table>
        </form>
    <p>New Farmer Register <a href="{%url 'ontology:farmer_reg' %}" style="text-decoration:none;">Here</a></p>
</center>




            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Footer -->
  <footer>
    <div class="container_24">
      <div class="wrapper">
        <div class="grid_24 footer-bg">
          <div class="hr-border-2"></div>
          <div class="wrapper">
            <div class="grid_7 suffix_1 prefix_1 alpha">
              <div class="copyright"> &copy; 2012 <strong class="footer-logo">AgroPlus</strong>
                <div>Website Template by <a target="_blank" href="http://www.templatemonster.com/">Templatemonster.com</a></div>
              </div>
            </div>
            <div class="grid_4">
              <h5 class="heading-1">Archives:</h5>
              <ul class="footer-list">
                <li><a href="#">October 2012</a></li>
                <li><a href="#">September 2012</a></li>
                <li><a href="#">August 2012</a></li>
                <li><a href="#">July 2012</a></li>
              </ul>
            </div>
            <div class="grid_4">
              <h5 class="heading-1">Links:</h5>
              <ul class="footer-list">
                <li><a href="#">Documentation</a></li>
                <li><a href="#">Plugins</a></li>
                <li><a href="#">Suggest Ideas</a></li>
                <li><a href="#">Support Forum</a></li>
              </ul>
            </div>
            <div class="grid_4">
              <h5 class="heading-1">Support:</h5>
              <ul class="footer-list">
                <li><a href="#">Special Proposition</a></li>
                <li><a href="#">Free Phone</a></li>
                <li><a href="#">Solutions</a></li>
              </ul>
            </div>
            <div class="grid_2 suffix_1 omega">
              <ul class="social-list">
                <li><a href="#"><img src="{% static 'images/social-icon-1.png' %}" alt=""></a></li>
                <li><a href="#"><img src="{% static 'images/social-icon-2.png' %}" alt=""></a></li>
                <li><a href="#"><img src="{% static 'images/social-icon-3.png' %}" alt=""></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
</div>
</body>
</html>

ontology/templates/ontology/knowledge_center_select_subcategory.html
{% load static %}
<html lang="en">
<head>
<title>AgroPlus</title>
<meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<script src="{% static 'js/jquery-1.7.1.min.js' %}"></script>
<script src="{% static 'js/superfish.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/tms-0.4.1.js' %}"></script>
<script src="{% static 'js/slider.js' %}"></script>
<!--[if lt IE 9]>
<script src="{% static 'js/html5.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/ie.css' %}">
<![endif]-->
</head>
<body>
<div class="main-bg">
  <!-- Header -->
  <header>
    <div class="inner">
      <h1 class="logo"><a href="{%url 'ontology:knowledge_center_home' %}">AgroPlus - Agriculture company</a></h1>
      <nav>
        <ul class="sf-menu">
          <li class="current"><a href="{%url 'ontology:knowledge_center_home' %}">home</a></li>
            <li> <a href="#">Manage</a>
            <ul>
                <li><a href="{%url 'ontology:manage_stock' %}">Stock</a></li>
                <li><a href="{%url 'ontology:manage_farmer' %}">Farmer</a></li>
                <li><a href="{%url 'ontology:manage_dealer' %}">Dealers</a></li>
            </ul>
          </li>
          <li> <a href="#">View</a>
            <ul>
                <li><a href="{%url 'ontology:view_all_farmers' %}">Farmers</a></li>
                <li><a href="{%url 'ontology:view_all_dealers' %}">Dealers</a></li>
        <li><a href="{%url 'ontology:knowledge_center_view_all_products' %}">Products</a></li>
        <li><a href="{%url 'ontology:view_complaints' %}">Complaints</a></li>
        <li><a href="{%url 'ontology:view_questions' %}">Questions</a></li>
        <li><a href="{%url 'ontology:admin_view_notification' %}">Notifications</a></li>
            </ul>
          </li>
            <li> <a href="#">Add</a>
            <ul>
                <li><a href="{%url 'ontology:knowledge_center_select_category' %}">Products</a></li>
                <li><a href="{%url 'ontology:add_knowledge_center_service' %}">Services</a></li>
                <li><a href="{%url 'ontology:add_knowledge_center_notification' %}">Notifications</a></li>
            </ul>
          </li>
           <li><a href="{%url 'ontology:logout' %}">Logout</a></li>
        </ul>
      </nav>
      <div class="clear"></div>
    </div>
    <div class="slider-container">
      <div class="mp-slider">
        <ul class="items">
          <li><img src="{% static 'images/slide-1.jpg' %}" alt="">
            <div class="banner mp-ban-1"><span class="row-1">putting our</span><span class="row-2">heart &amp; soul</span><span class="row-3">into the field</span></div>
          </li>
          <li><img src="{% static 'images/slide-2.jpg' %}" alt="">
            <div class="banner mp-ban-2"><span class="row-1">we have a strong</span><span class="row-2">agriculture</span><span class="row-3">heritage</span></div>
          </li>
          <li><img src="{% static 'images/slide-3.jpg' %}" alt="">
            <div class="banner mp-ban-3"><span class="row-1">growing clean</span><span class="row-2">and full of health</span><span class="row-3">products</span></div>
          </li>
        </ul>
      </div>
    </div>
    <a href="#" class="mp-prev"></a> <a href="#" class="mp-next"></a> </header>
  <!-- Content -->
  <section id="content">
    <div class="container_24">
      <div class="wrapper">
        <div class="grid_24 content-bg">
          <div class="wrapper">




           <center>
    {% if admin %}
    <h3>
       Select Sub Category
    </h3>
               {% if msg %}
               {{ msg }}
               {% endif %}
    <form method="post" action="{%url 'ontology:knowledge_center_add_product' admin.id %}">
        {% csrf_token %}
        <table>
            <tr>
                <td style="color:white;">Select Category&nbsp;&nbsp;</td>
                <td>
                    <select name="Subcategory" required="required">
                        <option value="">-----select category-----</option>
                    {% for s in sub %}
                        <option value="{{s.id}}">{{s.Name}}</option>
                    {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <td></td><td><input type="submit" value="Select" style="background-color:black; color:white; width:100px;"></td>
            </tr>
        </table>
    </form>
</center>
{% endif %}





          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Footer -->
  <footer>
    <div class="container_24">
      <div class="wrapper">
        <div class="grid_24 footer-bg">
          <div class="hr-border-2"></div>
          <div class="wrapper">
            <div class="grid_7 suffix_1 prefix_1 alpha">
              <div class="copyright"> &copy; 2012 <strong class="footer-logo">AgroPlus</strong>
                <div>Website Template by <a target="_blank" href="http://www.templatemonster.com/">Templatemonster.com</a></div>
              </div>
            </div>
            <div class="grid_4">
              <h5 class="heading-1">Archives:</h5>
              <ul class="footer-list">
                <li><a href="#">October 2012</a></li>
                <li><a href="#">September 2012</a></li>
                <li><a href="#">August 2012</a></li>
                <li><a href="#">July 2012</a></li>
              </ul>
            </div>
            <div class="grid_4">
              <h5 class="heading-1">Links:</h5>
              <ul class="footer-list">
                <li><a href="#">Documentation</a></li>
                <li><a href="#">Plugins</a></li>
                <li><a href="#">Suggest Ideas</a></li>
                <li><a href="#">Support Forum</a></li>
              </ul>
            </div>
            <div class="grid_4">
              <h5 class="heading-1">Support:</h5>
              <ul class="footer-list">
                <li><a href="#">Special Proposition</a></li>
                <li><a href="#">Free Phone</a></li>
                <li><a href="#">Solutions</a></li>
              </ul>
            </div>
            <div class="grid_2 suffix_1 omega">
              <ul class="social-list">
                <li><a href="#"><img src="{% static 'images/social-icon-1.png' %}" alt=""></a></li>
                <li><a href="#"><img src="{% static 'images/social-icon-2.png' %}" alt=""></a></li>
                <li><a href="#"><img src="{% static 'images/social-icon-3.png' %}" alt=""></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
</div>
</body>
</html>